source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GDTagListView_Example', :exclusive => true do
  pod "GDTagListView", :path => "../"
end

target 'GDTagListView_Tests', :exclusive => true do
  pod "GDTagListView", :path => "../"
  pod "Specta"
  pod "Expecta"
end
